language: node_js
node_js:
    - 'stable'
os:
    - linux
    - osx
before_install:
    - npm install -g gulp bower
install:
    - npm install
    - bower install
    - cd test && bower install && cd ../
    - gulp build
